coding_dojo_databricks_dbt:
  target: dev
  outputs:
    dev: &dev_config
      type: databricks
      catalog: main
      schema: dbt_jnadal
      host: "{{ env_var('DBT_HOST') }}"
      http_path: /sql/1.0/warehouses/b47df7379a47260a
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
      threads: 2

    prod:
      <<: *dev_config
      schema: silver
